version: '3.6'
services:
  mongo1:
    image: dannyben/alpine-mongo
    restart: always
    container_name: mongo1
    hostname: mongo1
    volumes:
      - mongodata1:/data/db
    ports:
      - 27017:27017
    entrypoint: ["/usr/bin/mongod", "--replSet", "my-mongo-set", "--bind_ip_all"]

  mongo2:
    image: dannyben/alpine-mongo
    restart: always
    container_name: mongo2
    hostname: mongo2
    ports:
      - 27018:27017
    entrypoint: ["/usr/bin/mongod", "--replSet", "my-mongo-set", "--bind_ip_all"]

  mongo3:
    image: dannyben/alpine-mongo
    restart: always
    container_name: mongo3
    hostname: mongo3
    volumes:
      - mongodata3:/data/db
    ports:
      - 27019:27017
    entrypoint: ["/usr/bin/mongod", "--replSet", "my-mongo-set", "--bind_ip_all"]

volumes:
  mongodata1:
    external: false
  mongodata2:
    external: false
  mongodata3:
    external: false
  mongostatus:
    external: false



## WIP
# version: '3.6'

# services:

#   # Primary
#   mongo1:
#     hostname: mongo1
#     container_name: mongo1
#     image: mongo
#     expose:
#       - 27017
#     ports:
#       - 30001:27017 
#     command: mongod --replSet my-mongo-set
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
#       - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    
#   # Secondary
#   mongo2:
#     hostname: mongo2
#     container_name: mongo2
#     image: mongo
#     expose:
#       - 27017
#     ports:
#       - 30002:27017
#     restart: always
#     command: mongod --replSet my-mongo-set
#     networks:
#       - my-mongo-cluster
#     depends_on:
#       - mongo1

#   # Secondary
#   mongo3:
#     hostname: mongo3
#     container_name: mongo3
#     image: mongo
#     expose:
#       - 27017
#     ports:
#       - 30003:27017
#     restart: always
#     command: mongod --replSet my-mongo-set
#     networks:
#       - my-mongo-cluster
#     depends_on:
#       - mongo1

# networks:
#   my-mongo-cluster:


